# Generated by Django 5.1.2 on 2024-10-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livrari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('meniu', models.CharField(max_length=100)),
                ('ora', models.DateTimeField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
