# Generated by Django 5.1.2 on 2024-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrari',
            name='ora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livrari',
            name='pret',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
